name = "Adventure Reloaded"
author = "badooga"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "981479ecbe7aeea9460939d994dc3c176545b55b2b4b2f9d7ec85edabf38c55d"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"
