name = "Adventure Reloaded"
author = "badooga"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51320e031c071210eba0ad1291a307dcf4912641fc43da55d9e9a1471e6d904e"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"
