name = "Adventure Reloaded"
author = "badooga"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fca7c51e3294c29edd33c992965af2afb3cab504151473ab58ed3777a63b112"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"
