name = "Adventure Reloaded"
author = "badooga"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ef4d35b5eb942a5fc799a1a261ba26123ed57d94139d562afb70340b17379e2"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"
