name = "Adventure Reloaded"
author = "badooga"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4e65035d5c779d68af7aa64e5488ca7c20f4f716ba63f2b01ae94060985e6b3"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"
