name = "Adventure Reloaded"
author = "badooga"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13712dda59df51720986d1fc4990aa90279c9fa3eb0b5dc11f6e921e44626b0d"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"
